### ISSUE TITLE
Clarifications sur l'installation

### ISSUE THREAD

**Issue by tardich** [MichelJourdain/HQuebec#1]
J'ai installé tous les cards nécessaires, copié Vue-Hydro-Quebec.yaml (et non Sous-Vue-Hydro-Quebec.yaml), copié le répertoire Cartes (que j'ai renommé HQ-Cartes, placé dans /config, et référé partout dans Vue-Hydro-Quebec.yaml (effectué cette modification pour tout conserver dans /config, et conserver la clareté de l'utilisation d'un répertoire custom). 

J'ai copié le contenu du fichier /packages/hydro_quebec_etats_des_periodes.yaml dans sensors.yaml (en fait, retiré la première ligne (sonsor:) (où mes custom sensors sont enregistrés) (le fichier sensors.yaml est appelé dans configuration.yaml `(sensor: !include sensors.yaml`)

La page Vue-Hydro-Quebec.yaml est appelée à partir de configuration.yaml:

```
lovelace:
  mode: storage
  dashboards:
    hydro-quebec-alt:
      filename: Vue-Hydro-Quebec.yaml
      title: Hydro-Quebec-Alt
      icon: 'ios:hydro-quebec-logo#fullcolor'
      show_in_sidebar: true
      mode: yaml
```

J'ai aussi changé toutes les références de sensor.hydroqc_maison_*  pour sensor.hydroqc_st_basile_* puisque c'est ainsi que tous mes entités sont rapportées dans mon HA.

Mais lorsque j'essaie de charger la page, elle est blanche. Rien d'affiché du tout. Où dois-je regarder pour essayer de comprendre ce qui se passe?  Je suis un peu perdu...

Merci.
